name: CI Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Test
        run: go test -race -v -coverprofile=profile.cov ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
